"""
P2P Messenger - Constants and Configuration
"""

# Network Ports
UDP_BROADCAST_PORT = 37020
TCP_PORT = 37021

# Timeouts (seconds)
PEER_TIMEOUT = 15.0
FILE_CHUNK_TIMEOUT = 5.0
HANDSHAKE_TIMEOUT = 15.0
CONNECTION_TIMEOUT = 10.0
TYPING_TIMEOUT = 3.0
MESSAGE_RETRY_COUNT = 3

# File Transfer
CHUNK_SIZE = 4096  # 4 KB
MAX_FILE_SIZE = 1024 * 1024 * 1024  # 1 GB

# Message Types
MSG_TYPE_TEXT = 0
MSG_TYPE_FILE = 1
MSG_TYPE_IMAGE = 2
MSG_TYPE_AUDIO = 3
MSG_TYPE_VIDEO = 4

# Message Statuses
MSG_STATUS_SENDING = 0
MSG_STATUS_SENT = 1
MSG_STATUS_DELIVERED = 2
MSG_STATUS_READ = 3
MSG_STATUS_ERROR = 4

# Contact Statuses
CONTACT_OFFLINE = 0
CONTACT_ONLINE = 1
CONTACT_AWAY = 2

# Packet Types
PACKET_TYPE_TEXT = 0x01
PACKET_TYPE_FILE_CHUNK = 0x02
PACKET_TYPE_FILE_INFO = 0x03
PACKET_TYPE_ACK = 0x04
PACKET_TYPE_NACK = 0x05
PACKET_TYPE_TYPING = 0x08
PACKET_TYPE_USER_INFO = 0x09
PACKET_TYPE_USER_ID = 0x0A
PACKET_TYPE_HANDSHAKE = 0x0B
PACKET_TYPE_CLOSE = 0x0C
PACKET_TYPE_READ_RECEIPT = 0x0D
PACKET_TYPE_DELIVERY_RECEIPT = 0x0E

# Crypto Settings
RSA_KEY_SIZE = 3072
CERT_VALIDITY_DAYS = 365 * 10  # 10 years

# App Settings
APP_NAME = "P2P Messenger"
APP_VERSION = "1.0.0"
DATA_DIR_NAME = ".p2p_messenger"

# UI Constants
WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 700
CHAT_WIDTH = 800
CHAT_HEIGHT = 600

# Colors
COLOR_PRIMARY = "#2E86AB"
COLOR_SECONDARY = "#A23B72"
COLOR_BACKGROUND = "#F1F1F1"
COLOR_CHAT_BG = "#FFFFFF"
COLOR_MESSAGE_OUT = "#DCF8C6"
COLOR_MESSAGE_IN = "#FFFFFF"
COLOR_TEXT = "#000000"
COLOR_TIMESTAMP = "#999999"
COLOR_ONLINE = "#4CAF50"
COLOR_OFFLINE = "#9E9E9E"
